### ISSUE TITLE
no input device error

### ISSUE THREAD

**Issue by skg4725** [djlastnight/KeyboardSplitterXbox#27] opened 2019-11-27 09:25 UTC
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/3896073/splitter_log.txt)

**Comment by djlastnight** [comment] 2019-12-13 19:33
Sorry I do not have much free time to see what is wrong. Thanks for your feedback. I hope this will be fixed soon.

**Comment by djlastnight** [comment] 2019-12-16 21:36
Yep, I was able to replicate this issue. It probably is caused by the recent windows update.
The solution:
**Manually** uninstall interception 1.0.0 driver, downloaded from [here](https://github.com/oblitum/Interception/releases/download/1.0.0/Interception.zip)
Open cmd.exe as admin, navigate to install-interception.exe folder and type
```install-interception /uninstall```. Reboot your PC.
Now run the KeyboardSplitter.exe - it will install the correct drivers and will ask you for a reboot.  

See how I did it in this video: https://youtu.be/ans2ArPO9V4

**Closed** 2019-12-16 21:40 UTC
