### ISSUE TITLE
Cannot connect ps4 controller

### ISSUE THREAD

**Issue by highasfukk** [djlastnight/KeyboardSplitterXbox#120] opened 2022-01-06 16:46 UTC
hello im new to github and all this and i just wanna play dont starve together splitscreen with my laptop's keyboard and mouse aaand my ps4 controller (i have dont starve cracked version in case that matters im poor xD) 
so trying to play dont starve splitscreen send me all te way to keyboard splitter where the guy in the vid just presses start and it works for him but when i open keyboard splitter and press start it tells me "slot is invalidated, controller_plug_in_failed 
plsss help :c

**Comment by highasfukk** [comment] 2022-01-06 16:47
![Bild_2022-01-06_174705](https://user-images.githubusercontent.com/97245502/148418815-504b8a04-3762-4d71-994b-636cc2fbd19a.png)

**Comment by iClapp** [comment] 2022-01-09 02:50
ive had the same issue alot

**Comment by iClapp** [comment] 2022-01-09 02:50
what i did was delete and re install it

**Comment by djlastnight** [comment] 2022-01-20 22:44
ps4 controllers and this app are incompatible - they use the same virtual bus to mount the virtual gamepads needed. Please let me know if you find a way to use ks + ps4

**Comment by djlastnight** [comment] 2022-03-19 11:21
Duplicate of #104

**Closed by djlastnight** 2022-03-19 11:21 UTC
