### ISSUE TITLE
2 keyboard + 2 dualshock

### ISSUE THREAD

**Issue by devpatel75** [djlastnight/KeyboardSplitterXbox#17] opened 2019-06-25 15:06 UTC
When I connect 2 keyboards and convert to Xbox controller and then I open x360ce my two dualshocks get detected and are successfully emulated but then it detects two keyboards but both the controllers are controlled by one keyboard. Note that when one keyboard is attached everything works perfectly.

**Comment by djlastnight** [comment] 2019-06-25 15:48
Make sure you set different keyboards for slot 1 and slot 2.
Can u send me a short video, explaining the problem.

**Comment by djlastnight** [comment] 2019-06-25 23:05
Do you use SCP for the dualshocks?

**Comment by devpatel75** [comment] 2019-06-28 09:57
Here's the video showcasing the problem
https://youtu.be/WQPZsAkfUd0
And I don't know what is a SCP.

**Comment by djlastnight** [comment] 2019-06-28 16:24
Thanks for your effort to create a video for me.

SPC is the virtual bus (ScpVBus), which is used to emulate virtual controllers. DS3 and DS4 drivers use it, KeyboardSplitter use it too. This may be a problem.

Note that you have to test the virtual controllers, using KS 'Controllers' > 'Test Xinput Controllers' menu for our testing purposes to ignore 3rd party apps custom configurations.
Also you may reveal the KS's Input Device Monitor, so I can see what you actually press.

Can you please try to:
1) change the 'Starting virtual controller user index' to 3 in KeyboardSplitter 'Tools' > 'Options' and then share the results.
2)  if 1) does not fix the issue - remove the dualshocks from your system and test KS again - share the results.
3) If none of this works, I will update the app, but I will need your support (probably TeamViewer session(s)).

Please let me know how are the things going.
Thanks for your feedback.

**Comment by devpatel75** [comment] 2019-06-28 17:51
1)The thing is I am using x360ce because I have 2 dualshocks.
2)Everything works perfectly when just 2 keyboards are connected when I don't have to use x360ce. When I use x360ce the problem occurs one keyboard gets emulated to two different controllers
3)I tried your "1 step", and did not work.

**Comment by djlastnight** [comment] 2019-06-28 21:43
ok write me blank a message to djlastnight@gmail.com

**Comment by djlastnight** [comment] 2019-07-05 00:52
Thanks for your feedback again. I hope that the issue is resolved with the new version 2.2.
Make sure '**Pass Through**' option in x360ce is **unchecked** for **every virtual** controller. See the screenshot attached.
![x360ce](https://user-images.githubusercontent.com/19281127/60691400-0ffeeb80-9ed8-11e9-9ab6-c1928ca44831.png)

**Closed** 2019-07-05 07:39 UTC
