### ISSUE TITLE
keyboard splitter not working

### ISSUE THREAD

**Issue by Zafyre** [djlastnight/KeyboardSplitterXbox#6] opened 2018-03-10 05:29 UTC
when i open keyboard splitter its showing no input devices are sound
pls tell me how to fix this

**Comment by Shob8sayala** [comment] 2018-03-10 05:53
I dont get what you want to say

**Comment by djlastnight** [comment] 2018-03-10 06:39
I will close issue #7 and answer here, because the issues (#6 and #7) are the same.
Did you installed vcredist 2013 x86, guys?

**Comment by sourav150418** [comment] 2018-04-15 19:01
same here .not working. I did 4 times clean format in windows 10 , now I am using 10133.73 , once it worked , this is the log file,,please help me sir
[log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/1913194/log.txt)

**Comment by djlastnight** [comment] 2018-04-15 19:04
sourav150418, please download the latest release (v2.0.0.3 atm) https://github.com/djlastnight/KeyboardSplitterXbox/releases/tag/2.0.0.3

**Comment by sourav150418** [comment] 2018-04-16 05:01
not opening in latest version but also working in 1.2.0.3 but when I playing this softwater not working properly
![screenshot 3](https://user-images.githubusercontent.com/38406000/38790819-4d1994a0-4161-11e8-9405-a4d6129027e5.png)

**Comment by djlastnight** [comment] 2018-04-16 12:55
sourav150418, I did not understand you well. Can you attach the log from the newest version, please?

**Comment by xtianrome26** [comment] 2018-04-16 14:13
It worked for me last time, but when i updated windows and downloaded it. when i run it. it says that it is not responding. idk why tho. i tried all versions and ends up the same. the latest tho when i run it, it not responds then suddenly my mouse and keyboard stop working. i had to restart my pc.

**Comment by xtianrome26** [comment] 2018-04-16 14:20
[log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/1915668/log.txt)
heres the log

**Comment by djlastnight** [comment] 2018-04-16 19:18
Guys, please make sure you have:
- Keyboard Splitter 2.0.0.3
- dot NET Framework 4 (or newer)
- DirectX 2010 June
- vcredist 2013 x86
- No "Scp Virtual Bus Driver" installed (Check at Device Manager -> System Devices).
If you have it - uninstall it and reboot your PC.
- No "Interception" driver installed.
If you are not sure - download command line tool from https://github.com/oblitum/Interception/releases/tag/1.0.0
Open cmd.exe as admin, navigate to install-interception.exe folder and type
install-interception /uninstall. Reboot your PC.

Now run the KeyboardSplitter.exe - it will install the correct drivers and will ask you for a reboot.

Hope this helps,
dj

**Comment by xtianrome26** [comment] 2018-04-17 09:42
i dont understand the interception part

**Comment by djlastnight** [comment] 2018-04-17 14:25
I will try to explain it as simple as I can:

1. Open D: and create new folder. Rename it 'Test'
2. Download interception release and extract it.
3. Move install-interception.exe to D:\Test
4. Open cmd.exe as admistrator.
5. Type cd D:
6. Type cd Test
7. Type install-interception. exe /uninstall

Hope this helps,
dj

**Comment by sourav150418** [comment] 2018-04-20 18:04
Same , it worked last time , then not working anymore, i will try again..

**Comment by sourav150418** [comment] 2018-04-20 18:33
Atlast Successfully working, juat uninstalled driver and installed dricetx june 2010 , thank you very much for details procedure 😊

**Comment by djlastnight** [comment] 2018-04-21 07:34
Nice. I am closing the issue.

**Comment by majbros07** [comment] 2018-06-01 18:41
System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) 

Please help me to solve it??

**Comment by majbros07** [comment] 2018-06-01 18:42
and tell me how to fix it with detail thanks???

**Comment by djlastnight** [comment] 2018-06-01 19:26
Hi. For now just install vcredist 2013 x86 as I already explained at one of my previous posts here. Hope this helps :)

**Comment by azmie111** [comment] 2018-06-09 10:42
Hi when i open dbc 17 with keyboard spliter it works for like 3-5 mins and it stops working

**Comment by djlastnight** [comment] 2018-06-09 10:53
It is a game related issue. Confirmed by many people.

You need to buy the game.

**Comment by krishnachouhan** [comment] 2018-10-19 06:59
If someone comes here...
Above solutions were working great but if problem still persists, then you might want to follow the dependencies.
For me, now even version 1.x is working fine after I looked up for the initial dependencies that i missed.
For my case, i followed the following requirements which can be found at https://github.com/nefarius/ScpToolkit...
```
Installation requirements
Microsoft Windows Vista/7/8/8.1/10 x86 or amd64
Microsoft .NET Framework 4.5
Microsoft Visual C++ 2010 Redistributable Package
Microsoft Visual C++ 2013 Runtime
DirectX Runtime
Xbox 360 Controller driver
Already integrated in Windows 8.x or greater
At least one supported Sony DualShock 3/4 controller (see Compatible Controllers)
Administrator rights during driver setup
```

**Comment by Hrishihari** [comment] 2019-03-21 08:22
My keyboard splitter is not working
It is showing log .txt error
I did what you typed recently
But also didnt worked

**Comment by deltatask** [comment] 2019-07-21 13:56
**I CANT USE X-MINI AND Y_MINI AT SAME  TIME PLZ HELP ME ABOUT THIS**

**Comment by djlastnight** [comment] 2019-07-21 13:59
> **I CANT USE X-MINI AND Y_MINI AT SAME TIME PLZ HELP ME ABOUT THIS**

Please refer to #12 and explain your problem there (with details).

**Comment by deltatask** [comment] 2019-07-23 17:15
How can I download xinput controller tester.if you have link plz give me.

**Comment by djlastnight** [comment] 2019-07-27 11:24
It is not a dedicated app, but builtin at the KeyboardSplitter. You will find it at the file menu

**Comment by thirdeyeblind007** [comment] 2019-09-03 15:16
Keyboardsplitter not running..  Check log file.. What should I do.. I have done almost all the steps written above...



![log](https://user-images.githubusercontent.com/54854568/64186082-dae92800-ce8b-11e9-8747-8cf95cbfd31c.jpg)

**Comment by samisk0096** [comment] 2019-10-13 07:39
Hey i am unable to start the keyboard splitter please help me i am sending you a file 
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/3721528/splitter_log.txt)

**Comment by djlastnight** [comment] 2019-10-13 08:58
Hey. Always download the latest version when you have issues. Please try it and tell if the problem still persists

**Comment by samisk0096** [comment] 2019-10-13 13:08
I tried but not working what should I do not version is working previously
12.0.2 worked but now it is not working I have everything thing installed
vc++ .net directx actually I use Windows 8.1 recently I have formatted
windows 8.1 and again installed previously it used to work but now it is
not working. Please help me sir.

**Comment by krishnachouhan** [comment] 2019-10-13 16:29
@samisk0096  never saw this error but similar error I had experience and that generally happens when architecture was x32 bit and application used 64x.  (or vice-versa)

**Comment by djlastnight** [comment] 2019-10-13 19:05
Yes, bad image format exception is thrown by .NET, when you use the wrong arch library (x86 or x64).
Are you sure that you installed the right vcredist.
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe

**Comment by manojvarma321** [comment] 2019-12-04 12:23
> when i open keyboard splitter its showing no input devices are sound
> pls tell me how to fix this

i to got the same problem

**Comment by manojvarma321** [comment] 2019-12-04 12:24
#27

**Comment by manojvarma321** [comment] 2019-12-04 12:25
![Screenshot (34)](https://user-images.githubusercontent.com/58514542/70142410-2e535800-16bf-11ea-8f95-dd3f10010178.png)

**Comment by manojvarma321** [comment] 2019-12-04 12:25
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/3921765/splitter_log.txt)

**Comment by djlastnight** [comment] 2019-12-31 00:57
Hey guys, there is another (easier) way to get rid of the bugged interception driver (probably caused by a recent windows update). I believe this is causing the 'No input devices were detected' error.

That's why I just wrote [Interception GUI Uninstaller application](https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true). Try it out.

**Comment by samisk0096** [comment] 2020-01-13 07:18
It is showing me bad format exception no matter what I do

**Comment by samisk0096** [comment] 2020-01-13 07:19
My OS is windows 8.1 x64 build 9600 I have all runtime installed still it
shows me bad image format exception

**Comment by msdhoni77** [comment] 2020-03-25 07:02
@djlastnight.

I followed all the steps,

Keyboard Splitter 2.0.0.3
dot NET Framework 4 (or newer)
DirectX 2010 June
vcredist 2013 x86
No "Scp Virtual Bus Driver" installed (Check at Device Manager -> System Devices).
If you have it - uninstall it (check the 'Delete the driver software for this device' checkbox and reboot your PC.
No "Interception" driver installed.
If you are not sure - download command line tool from https://github.com/oblitum/Interception/releases/tag/1.0.0
Open cmd.exe as admin, navigate to install-interception.exe folder and type
install-interception /uninstall. Reboot your PC.

But still, if I open keyboard splitter a white screen opens and it is closing automatically.

**Comment by rajkiran150** [comment] 2020-03-29 14:52
![Capture](https://user-images.githubusercontent.com/62843374/77852198-e8d11280-71fa-11ea-8e5a-d6da61b48ab5.PNG)
i couldn't even install keyboard splitter plss suggest me something i need to install

**Comment by akki1998z** [comment] 2020-04-03 08:46
softwere open then blank windiw coming up and then immidialty closed pls tell mi solution in log te give setting is not found

**Comment by srini199416** [comment] 2020-08-16 22:15
Hi i m also geeting error message  as 

Unexcepted app crash occured
Please refer to splitter_log.txt for more details 

Please kindly help me to reslove and fix the issuec

**Comment by suni4419** [comment] 2020-09-02 13:40
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Application started from C:\Users\HP\Downloads\KeyboardSplitter_2.0.0.5b\KeyboardSplitter.exe
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - User has write permissions: True
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.5
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - OS version: Windows 10 x64 build 18363 
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Setting environment
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Extracting native resources
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 24 MB] - Loading SplitterCore 2.0.0.5
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 24 MB] - Loading Interceptor 2.0.0.5
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.5
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 25 MB] - Interception driver state: not installed
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 25 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Wed] 02 Sep, 2020 [19:04:08] [Mem: 25 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Prasad43** [comment] 2020-09-05 10:12
@djlastnight 

App will not open, it just shows me a white screen for 5-10 seconds and then closes.Can you please assist

please note: I have followed all the steps in #28 (comment) 

Log sheet:

[Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application started from D:\KeyboardSplitter.exe
[Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - User has write permissions: True
[Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - OS version: Windows 10 x64 build 18362
[Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Setting environment
[Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Extracting native resources
[Sat] 05 Sep, 2020 [15:27:09] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Interception driver state: installed
[Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - ScpVBus driver state: installed
[Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Xbox accessories driver state: installed
[Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Loading XinputWrapper 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Settings file not found
[Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Main window loaded

**Comment by samisk0096** [comment] 2020-09-06 06:40
> @djlastnight
> 
> App will not open, it just shows me a white screen for 5-10 seconds and then closes.Can you please assist
> 
> please note: I have followed all the steps in #28 (comment)
> 
> Log sheet:
> 
> [Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application started from D:\KeyboardSplitter.exe
> [Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - User has write permissions: True
> [Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
> [Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - OS version: Windows 10 x64 build 18362
> [Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Setting environment
> [Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Extracting native resources
> [Sat] 05 Sep, 2020 [15:27:09] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
> [Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
> [Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
> [Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Interception driver state: installed
> [Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - ScpVBus driver state: installed
> [Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Xbox accessories driver state: installed
> [Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Loading XinputWrapper 2.0.0.3
> [Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Settings file not found
> [Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Main window loaded

Try again loading it. If problem persist disable scpdriver from device manager

**Comment by samisk0096** [comment] 2020-09-06 06:41
This is the best app for playing Xbox games I loved it.

**Comment by samisk0096** [comment] 2020-09-06 06:42
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Application started from C:\Users\HP\Downloads\KeyboardSplitter_2.0.0.5b\KeyboardSplitter.exe
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - User has write permissions: True
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.5
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - OS version: Windows 10 x64 build 18363
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Setting environment
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 18 MB] - Extracting native resources
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 24 MB] - Loading SplitterCore 2.0.0.5
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 24 MB] - Loading Interceptor 2.0.0.5
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.5
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 25 MB] - Interception driver state: not installed
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 25 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
> [Wed] 02 Sep, 2020 [19:04:08] [Mem: 25 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
> at VirtualXbox.NativeMethods.VBusExists()
> at KeyboardSplitter.App.ReportDriversState()
> at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
> at System.Windows.Application.OnStartup(StartupEventArgs e)
> at System.Windows.Application.<.ctor>b__1_0(Object unused)
> at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Install Xbox driver from Microsoft website or search on Google

**Comment by Masood321** [comment] 2020-09-07 16:59
[Mon] 07 Sep, 2020 [21:51:28] [Mem: 15 MB] - Application started from G:\masood files\Hitman Absolution\mk10\Don.Bradman.Cricket.17\DBC17\KeyboardSplitter.exe
[Mon] 07 Sep, 2020 [21:51:28] [Mem: 15 MB] - User has write permissions: True
[Mon] 07 Sep, 2020 [21:51:28] [Mem: 15 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Mon] 07 Sep, 2020 [21:51:28] [Mem: 16 MB] - OS version: Windows 8 x64 build 9200 
[Mon] 07 Sep, 2020 [21:51:28] [Mem: 16 MB] - Setting environment
[Mon] 07 Sep, 2020 [21:51:28] [Mem: 17 MB] - Loading interception 1.00
[Mon] 07 Sep, 2020 [21:51:28] [Mem: 17 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 07 Sep, 2020 [21:51:29] [Mem: 21 MB] - Loading SplitterCore 2.2.0.0
[Mon] 07 Sep, 2020 [21:51:29] [Mem: 21 MB] - Loading Interceptor 2.2.0.0
[Mon] 07 Sep, 2020 [21:51:29] [Mem: 21 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 07 Sep, 2020 [21:51:29] [Mem: 22 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Mon] 07 Sep, 2020 [21:51:30] [Mem: 22 MB] - System.Management.ManagementException: Not found 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at Interceptor.InterceptionDriver.get_DriverState() 
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

please anyone help me to solve this problem.

**Comment by Prasad43** [comment] 2020-09-09 04:39
> > @djlastnight
> > App will not open, it just shows me a white screen for 5-10 seconds and then closes.Can you please assist
> > please note: I have followed all the steps in #28 (comment)
> > Log sheet:
> > [Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application started from D:\KeyboardSplitter.exe
> > [Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - User has write permissions: True
> > [Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
> > [Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - OS version: Windows 10 x64 build 18362
> > [Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Setting environment
> > [Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Extracting native resources
> > [Sat] 05 Sep, 2020 [15:27:09] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
> > [Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
> > [Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
> > [Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Interception driver state: installed
> > [Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - ScpVBus driver state: installed
> > [Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Xbox accessories driver state: installed
> > [Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Loading XinputWrapper 2.0.0.3
> > [Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Settings file not found
> > [Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Main window loaded
> 
> Try again loading it. If problem persist disable scpdriver from device manager

@djlastnight @samisk0096 - I have tried disabling the SCP Driver and re-installed and repeated the entire process... still the same issue as mentioned above.... Kindly please assist 

Here is the new splitter_log 

[Wed] 09 Sep, 2020 [09:59:32] [Mem: 18 MB] - Application started from D:\KeyboardSplitter.exe
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 18 MB] - User has write permissions: True
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 18 MB] - OS version: Windows 10 x64 build 18362 
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 18 MB] - Setting environment
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 18 MB] - Extracting native resources
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 25 MB] - Interception driver state: installed
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 25 MB] - ScpVBus driver state: installed
[Wed] 09 Sep, 2020 [09:59:32] [Mem: 25 MB] - Xbox accessories driver state: installed
[Wed] 09 Sep, 2020 [09:59:33] [Mem: 36 MB] - Loading XinputWrapper 2.0.0.3
[Wed] 09 Sep, 2020 [09:59:33] [Mem: 36 MB] - Settings file not found
[Wed] 09 Sep, 2020 [09:59:33] [Mem: 36 MB] - Main window loaded
[Wed] 09 Sep, 2020 [09:59:33] [Mem: 36 MB] - Creating splitter with 2 slots 
[Wed] 09 Sep, 2020 [09:59:33] [Mem: 37 MB] - Creating input manager

**Comment by rohansingh2** [comment] 2020-09-15 18:40
@djlastnight 
![Screenshot (1)](https://user-images.githubusercontent.com/71347052/93250731-17f72400-f748-11ea-8405-ad4a4edd33d4.png)
[Tue] 15 Sep, 2020 [11:33:19] [Mem: 8 MB] - Application started from D:\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Tue] 15 Sep, 2020 [11:33:19] [Mem: 8 MB] - User has write permissions: True
[Tue] 15 Sep, 2020 [11:33:19] [Mem: 9 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Tue] 15 Sep, 2020 [11:33:19] [Mem: 9 MB] - OS version: Windows 10 x64 build 18362 
[Tue] 15 Sep, 2020 [11:33:19] [Mem: 9 MB] - Setting environment
[Tue] 15 Sep, 2020 [11:33:20] [Mem: 9 MB] - Extracting native resources
[Tue] 15 Sep, 2020 [11:33:20] [Mem: 12 MB] - Loading SplitterCore 2.0.0.3
[Tue] 15 Sep, 2020 [11:33:20] [Mem: 12 MB] - Loading Interceptor 2.0.0.3
[Tue] 15 Sep, 2020 [11:33:20] [Mem: 12 MB] - Loading VirtualXbox 2.0.0.3
[Tue] 15 Sep, 2020 [11:33:24] [Mem: 12 MB] - Interception driver state: not installed
[Tue] 15 Sep, 2020 [11:33:24] [Mem: 12 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Tue] 15 Sep, 2020 [11:33:24] [Mem: 12 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)





I HAVE TRIED EVERTHING YOU HAVE SAID ABOOVE BUT IT'S NOT WORKING.PLEASE HELP!!

**Comment by marclaj1960** [comment] 2020-10-03 05:18
I have a problem after opening the application at soon that I approach the mouse pointer the computer jammed. The mouse and the keyboard are stuck and I don't have any choice but to reboot.

Windows 10 v19041.508
Directx 12
Framework 4.8.04084
vcredist 15.0.179
Keyboard splitter 2.2.0.0

 I did uninstalled "Scp Virtual Bus Driver" and check if "Interception" driver was installed. It was installed into the game directory.

Can you help ?

Thanks!

**Comment by codeclassic** [comment] 2020-10-29 08:37
I have downloaded the latest version Keyboard.Splitter.2.2.0.0, it shows a small blank (white) window then disappears. Please help

**Comment by FABCPY** [comment] 2020-12-03 18:56
I want to ask you if you can help me with a problem.
Download and install keyboardSplitter 2.2.0.0 software from this page below.

https://www.softpedia.com/get/System/System-Miscellaneous/Gaming-Keyboard-Splitter.shtml#disqus_thread

After installing I asked to restart windows 10, and what happens is that it no longer recognizes my keyboard and mouse, I can do nothing within windows but turn the computer off and on with the physical button.

**Comment by djlastnight** [comment] 2021-04-19 11:48
Why do you download from 3rd party sites? This is an open source app - you can directly download **MY** builds from github.
I can guarantee they are virus free and so on. You can even download the source code and build your own keyboard splitter.

Closing this, because it seems a lot of people does NOT follows the written here: https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
then report a problem.

**Closed by djlastnight** 2021-04-19 11:48 UTC

**Comment by SINGHALR77** [comment] 2021-05-31 14:33
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/6570894/splitter_log.txt)
please help

**Comment by djlastnight** [comment] 2021-07-21 16:06
@SINGHALR77 Install all this https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites

**Comment by LoveSiick** [comment] 2021-11-02 17:22
Hey thanks a lot it's working now as before, i still have the problem with mouse movement on win 10 but no matter, thanks for the help!

**Comment by MasterDush** [comment] 2021-11-02 19:18
> I will try to explain it as simple as I can:
> 
> 1. Open D: and create new folder. Rename it 'Test'
> 2. Download interception release and extract it.
> 3. Move install-interception.exe to D:\Test
> 4. Open cmd.exe as admistrator.
> 5. Type D:
> 6. Type cd Test
> 7. Type install-interception. exe /uninstall
> 
> Hope this helps, dj

I have a problem with this
Error deleting \system32\drivers\keyboard.sys

**Comment by Mwesigyesteven** [comment] 2024-04-04 09:51
> ![Screenshot (34)](https://user-images.githubusercontent.com/58514542/70142410-2e535800-16bf-11ea-8f95-dd3f10010178.png)

i also have the same problem

**Comment by Mwesigyesteven** [comment] 2024-04-04 09:52
no input device were detected
