### ISSUE TITLE
Keyboard Splitter is jamming when approaching the mouse

### ISSUE THREAD

**Issue by marclaj1960** [djlastnight/KeyboardSplitterXbox#70] opened 2020-10-02 20:01 UTC
I tried to install and use the latest version of Keyboard Splitter but every time after the apps is opened and approach the mouse pointer everything jammed. My only option is to reboot. I did check if I have the proper DX, Framework, etc. I removed the Scp Virtual Bus Driver and reinstall but still the same problem.

Do you have any solution or why ?

I'm using Windows 10 64

Thanks !

**Comment by djlastnight** [comment] 2020-10-25 19:57
Hi there. Obviously the problem is not SCP related, but the keyboard driver.
You are the first person, reporting such issue, so I can't tell for sure where the problem is.
You can try to run this [app](https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true) and let me know if this works.
Thanks in advance.

**Comment by djlastnight** [comment] 2021-04-19 13:20
No answer. Closing.

**Closed by djlastnight** 2021-04-19 13:20 UTC
